name: cerberus
channels:
  - conda-forge
  - defaults
dependencies:
  - docopt=0.6.2
  - hdf5=1.12.1
  - joblib=1.1.0
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openslide
  - pandas=1.3.5
  - pillow=9.0.1
  - pip=21.2.2
  - progress=1.5
  - python=3.7.12
  - pyyaml=6.0
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - shapely=1.7.1
  - termcolor=1.1.0
  - tqdm=4.64.0
  - yaml=0.2.5
  - pip:
    - imgaug==0.4.0
    - opencv-python==4.6.0.66
    - opencv-python-headless==4.5.5.64
    - openslide-python==1.2.0
    - seaborn==0.11.2
    - tensorboardx==2.5.1
    - tiatoolbox==1.3.1